### ISSUE TITLE
`npm build` doesn't run

### ISSUE THREAD

**Issue by LynxEyes** [mjmlio/mjml-component-boilerplate#21]
Hi!

I've been trying to run this boilerplate, been unsuccessful so far.
I've tried to run it on my mac, didn't - issue:

I've then tried to run this on a docker container and found some new issues: `npm run build` fails:

```
root@f7f183d586b2:/app# npm install
npm WARN test@1.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 766 packages from 421 contributors and audited 13917 packages in 17.573s
found 581 vulnerabilities (42 low, 487 moderate, 52 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@f7f183d586b2:/app# npm run build

> test@1.0.1 build /app
> gulp build

[20:11:59] Failed to load external module @babel/register
[20:11:59] Requiring external module babel-register
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/app/node_modules/natives/index.js:137:5)
    at require (/app/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/app/node_modules/natives/index.js:137:5)
    at require (/app/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/app/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/app/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-20T20_11_59_712Z-debug.log
```

I guess this means that there is something wrong with some babel configuration, I just don't really know what it is.. Any idea? Thanks.

**Comment by kmcb777** [comment]
Hi @LynxEyes according to this issue https://github.com/gulpjs/gulp/issues/2246, it's related to node 11
Seems like `npm install natives@1.1.6` solved the problem for many people
However, according this issue https://github.com/gulpjs/gulp/issues/2246 it's not recommended to use gulp 3.9 with node 11, so you should use a previous node version. (you'll probably have to remove your node_modules and install again)

**Comment by LynxEyes** [comment]
Using natives 1.1.6 solves but.. 🤔 there might be some other thing at play here.
Here is my docker-compose file:

```yml
version: "2"
volumes:
  mjml-sync: { external: true }
  mjml-config: { driver: local }

services:
  #####################################
  # Development-specific applications #
  #####################################

  mjml:
    image: node:10.14.2
    command: ["bin/mjml"]
    environment:
      HISTFILE: "/config/.bash_history"
    volumes:
      - 'mjml-sync:/app:nocopy'
      - 'mjml-config:/config'
    working_dir: /app
```

I'm using node 10.14.2, so, should have worked maybe??
Anyway, for what matters, I'm gonna consider this fixed since `natives@1.1.6` works.

Thanks!!
